In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("data.csv")

In [4]:
df

Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [5]:
df.dropna()

Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12/11/2019
6  Alice  25.0     New York      F  alice@example.com    1/5/2021
7  Alice  25.0     New York      F  alice@example.com    1/5/2021

In [6]:
df.dropna(axis=1)

City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [7]:
df.fillna(0)

Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [8]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [31]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [33]:
df

Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [39]:
df.dropna()

Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12/11/2019
6  Alice  25.0     New York      F  alice@example.com    1/5/2021
7  Alice  25.0     New York      F  alice@example.com    1/5/2021

In [51]:
df.fillna(df["Age"].mean())

Name        Age         City Gender              Email   Join Date
0      Alice  25.000000     New York      F  alice@example.com    1/5/2021
1    Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
2        Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3    Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
4      David  22.000000       Mumbai      M  david@example.com  12/11/2019
5  25.833333  28.000000        Delhi      F     eve@domain.com   25.833333
6      Alice  25.000000     New York      F  alice@example.com    1/5/2021
7      Alice  25.000000     New York      F  alice@example.com    1/5/2021
8    Charlie  25.833333        Delhi      M    charlie@example  20-07-2021

In [67]:
df.fillna(df["Age"].mean())

Name        Age         City Gender              Email   Join Date
0      Alice  25.000000     New York      F  alice@example.com    1/5/2021
1    Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
2        Bob  30.000000  Los Angeles      M    bob@example.com  15-06-2020
3    Charlie  25.833333        Delhi      M    charlie@example  20-07-2021
4      David  22.000000       Mumbai      M  david@example.com  12/11/2019
5  25.833333  28.000000        Delhi      F     eve@domain.com   25.833333
6      Alice  25.000000     New York      F  alice@example.com    1/5/2021
7      Alice  25.000000     New York      F  alice@example.com    1/5/2021
8    Charlie  25.833333        Delhi      M    charlie@example  20-07-2021

In [73]:
df.fillna(df.ffill())

Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5    David  28.0        Delhi      F     eve@domain.com  12/11/2019
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [95]:
df = pd.read_csv("data.csv")
df

Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [81]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [101]:
df.drop_duplicates()

Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [103]:
df.duplicated(subset=["Name","Age"])

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [105]:
df["Name"].str.upper()

0      ALICE
1    CHARLIE
2        BOB
3    CHARLIE
4      DAVID
5        NaN
6      ALICE
7      ALICE
8    CHARLIE
Name: Name, dtype: object

In [107]:
df

Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [145]:
df["City"].str.contains("Delhi")

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [153]:
type(df["City"].str.contains("Delhi"))

pandas.core.series.Series

In [163]:
mail = df["Email"].str.split("@")

In [168]:
pd.DataFrame(mail)

Email
0  [alice, example.com]
1    [charlie, example]
2    [bob, example.com]
3    [charlie, example]
4  [david, example.com]
5     [eve, domain.com]
6  [alice, example.com]
7  [alice, example.com]
8    [charlie, example]

In [174]:
df2 = df.dropna().copy()
df2

Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12/11/2019
6  Alice  25.0     New York      F  alice@example.com    1/5/2021
7  Alice  25.0     New York      F  alice@example.com    1/5/2021

In [26]:
import numpy as np
arr = np.array([1,2,3,4])

a= [1,2,6,8,9]
b = ["shubham",32]

In [30]:
for item in b:
    a.append(item)
a
    

[1, 2, 6, 8, 9, 'shubham', 32]

In [32]:
a[2] = 32

In [34]:
a

[1, 2, 32, 8, 9, 'shubham', 32]

In [31]:
import pandas as pd 
df = pd.read_csv("data.csv")
df

Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com    1/5/2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12/11/2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com    1/5/2021
7    Alice  25.0     New York      F  alice@example.com    1/5/2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [61]:
df2 = df.dropna().copy()
df2

Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com    1/5/2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12/11/2019
6  Alice  25.0     New York      F  alice@example.com    1/5/2021
7  Alice  25.0     New York      F  alice@example.com    1/5/2021

In [67]:
df2["Age Group"] = df2["Age"].apply(lambda x:"Adult" if x >=23 else "Minor")
df2

Name   Age         City Gender              Email   Join Date Age Group
0  Alice  25.0     New York      F  alice@example.com    1/5/2021     Adult
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult
4  David  22.0       Mumbai      M  david@example.com  12/11/2019     Minor
6  Alice  25.0     New York      F  alice@example.com    1/5/2021     Adult
7  Alice  25.0     New York      F  alice@example.com    1/5/2021     Adult

In [85]:
def sports(x):
    return ("badminton" if x == "F" else "football")
df2["Sport"] = df2["Gender"].apply(sports)

df2

Name   Age         City Gender              Email   Join Date Age Group  \
0  Alice  25.0     New York      F  alice@example.com    1/5/2021     Adult   
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Adult   
4  David  22.0       Mumbai      M  david@example.com  12/11/2019     Minor   
6  Alice  25.0     New York      F  alice@example.com    1/5/2021     Adult   
7  Alice  25.0     New York      F  alice@example.com    1/5/2021     Adult   

       Sport  
0  badminton  
2   football  
4   football  
6  badminton  
7  badminton

In [87]:
gender_map = {"M" : "Male", "F" : "Female","O":"Other"}
df2["Gender"] = df2["Gender"].map(gender_map)
df2

Name   Age         City  Gender              Email   Join Date Age Group  \
0  Alice  25.0     New York  Female  alice@example.com    1/5/2021     Adult   
2    Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Adult   
4  David  22.0       Mumbai    Male  david@example.com  12/11/2019     Minor   
6  Alice  25.0     New York  Female  alice@example.com    1/5/2021     Adult   
7  Alice  25.0     New York  Female  alice@example.com    1/5/2021     Adult   

       Sport  
0  badminton  
2   football  
4   football  
6  badminton  
7  badminton

In [105]:
city_replace = {"Delhi":"New Delhi", "Mumbai":"New Mumbai", "New York": "Raju bhai ka dhaba"} 


In [107]:
df2["City"] = df2["City"].replace(city_replace)
df2

Name   Age                City  Gender              Email   Join Date  \
0  Alice  25.0  Raju bhai ka dhaba  Female  alice@example.com    1/5/2021   
2    Bob  30.0         Los Angeles    Male    bob@example.com  15-06-2020   
4  David  22.0          New Mumbai    Male  david@example.com  12/11/2019   
6  Alice  25.0  Raju bhai ka dhaba  Female  alice@example.com    1/5/2021   
7  Alice  25.0  Raju bhai ka dhaba  Female  alice@example.com    1/5/2021   

  Age Group      Sport  
0     Adult  badminton  
2     Adult   football  
4     Minor   football  
6     Adult  badminton  
7     Adult  badminton

In [109]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Shubham", "Amit", "Priya", "Shubham", np.nan, "Ravi", "Kiran"],
    "Age": [25, 30, 22, 25, 28, np.nan, 30],
    "Salary": [50000, np.nan, 45000, 50000, 40000, 47000, np.nan],
    "Department": ["IT", "HR", "Finance", "IT", None, "HR", "Finance"]
}

df = pd.DataFrame(data)
print(df)


      Name   Age   Salary Department
0  Shubham  25.0  50000.0         IT
1     Amit  30.0      NaN         HR
2    Priya  22.0  45000.0    Finance
3  Shubham  25.0  50000.0         IT
4      NaN  28.0  40000.0       None
5     Ravi   NaN  47000.0         HR
6    Kiran  30.0      NaN    Finance


In [113]:
df.head()

Name   Age   Salary Department
0  Shubham  25.0  50000.0         IT
1     Amit  30.0      NaN         HR
2    Priya  22.0  45000.0    Finance
3  Shubham  25.0  50000.0         IT
4      NaN  28.0  40000.0       None

In [115]:
df.shape

(7, 4)

In [121]:
df.columns

Index(['Name', 'Age', 'Salary', 'Department'], dtype='object')

In [123]:
df.isnull

<bound method DataFrame.isnull of       Name   Age   Salary Department
0  Shubham  25.0  50000.0         IT
1     Amit  30.0      NaN         HR
2    Priya  22.0  45000.0    Finance
3  Shubham  25.0  50000.0         IT
4      NaN  28.0  40000.0       None
5     Ravi   NaN  47000.0         HR
6    Kiran  30.0      NaN    Finance>

In [131]:
df.isnull().sum()

Name          1
Age           1
Salary        2
Department    1
dtype: int64

In [133]:
df["Age"].isnull()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
Name: Age, dtype: bool

In [137]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
df

Name        Age   Salary Department
0  Shubham  25.000000  50000.0         IT
1     Amit  30.000000      NaN         HR
2    Priya  22.000000  45000.0    Finance
3  Shubham  25.000000  50000.0         IT
4      NaN  28.000000  40000.0       None
5     Ravi  26.666667  47000.0         HR
6    Kiran  30.000000      NaN    Finance

In [139]:
import numpy as np


In [145]:
arr = np.array(np.arange(1,11))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [149]:
arr = np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [151]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [153]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [159]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [161]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [173]:
np.random.randint(1,51,50)


array([41, 49, 45, 36, 28, 13, 43,  3, 50,  5, 44, 11, 10, 38, 40, 13, 28,
       13, 33,  4, 34, 13, 27, 10, 27, 23, 46, 47, 12, 45, 50, 45, 32,  7,
       48, 16, 20, 34, 10, 35, 38,  5, 41, 13, 25, 35, 30, 10, 12, 18])

In [181]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [189]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [221]:
arr = np.arange(1, 10).reshape(3, 3)
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [223]:
arr[-1,:]

array([7, 8, 9])

In [225]:
arr[1:4,1:4]

array([[5, 6],
       [8, 9]])

In [227]:
arr[arr % 2 ==0]

array([2, 4, 6, 8])

In [229]:
arr.sum()

45

In [231]:
arr.sum(0)

array([12, 15, 18])