In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
flat = arr.flatten()

In [13]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
flat[0:5]

array([1, 2, 3, 4, 5])

In [29]:
flat[::3]

array([1, 4, 7])

In [31]:
flat


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
b = flat[2:5].copy() #this is not a slice because we are using the copy method
b

array([55,  4,  5])

In [49]:
b[0] = 55556669

In [51]:
b

array([55556669,        4,        5])

In [53]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
flat

array([ 1,  2, 55,  4,  5,  6,  7,  8,  9])

In [59]:
flat[[1,2,5]]

array([ 2, 55,  6])

In [63]:
flat[flat<5]

array([1, 2, 4])