In [5]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr[0]

array([1, 2, 3])

In [9]:
arr[1]

array([4, 5, 6])

In [11]:
arr[2]

array([7, 8, 9])

In [27]:
np.sum(arr,axis=1)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr[0][2]

3

In [61]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [63]:
arr3D = np.array([[[1, 2, 3], 
                   [4, 5, 6]],
                  [
                      [7, 8, 9], 
                      [10, 11, 12]
                  ]
                 ])


In [101]:
arr3D[:,0,:] = 0

In [103]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])

In [105]:
 # numpy data types

In [125]:
arr = np.array([12,45,35,9])


In [131]:
arr.dtype

dtype('int32')

In [181]:
arr1 = arr.astype('float64')
arr1

array([12., 45., 35.,  9.])

In [177]:
arr1.dtype

dtype('int64')

In [171]:
arr.nbytes

16

In [173]:
arr1.nbytes

16