In [17]:
import numpy as np
import time

In [5]:
l1 = [1,2,3]
l2 = [4,5,6]

In [9]:
list(zip(l1,l2))

[(1, 4), (2, 5), (3, 6)]

In [ ]:
# using numpy arreys
import numpy as np
import time
size = 1_000_000_00
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))
    
start = time.time()
add = l1 + l2

end = time.time()
print("timing of" ,add[0:10] ,'\n',end-start, )
    

In [101]:
# using python list

import time

size = 1_000_000_00
l1 = list(range(size))
l2 = list(range(size))
    
start = time.time()
add = [x+y for x, y in zip(l1,l2)]
    
end = time.time()
print("timing of" ,add[0:10],end-start)

timing of [0, 2, 4, 6, 8, 10, 12, 14, 16, 18] 31.163822650909424


In [4]:
import numpy as np
arr = np.array([[1,2,4,3],[4,5,3,6]])

In [6]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(2, 4)

In [10]:
import sys

list_data = list(range(1000000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8000056000000 bytes
NumPy array size: 4000000 bytes


In [13]:
arr = np.array(list[1,2,3])

In [27]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
arr = np.ones((5,5))

In [93]:
np.full((4,5),9)

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [79]:
arr = np.eye(3)

In [51]:
np.arange(5,51,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [99]:
arr = np.linspace(0,10,5)
lineSpace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [101]:
arr.shape

(5,)

In [105]:
a = np.full((4,5),9)
a

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [109]:
a.shape


(4, 5)

In [123]:
a.reshape(5,4)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [151]:
import numpy as np
arr = np.array([])
for i in range(1,51):
    arr = np.append(arr,i)
arr

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [163]:
arr.reshape(10,5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.],
       [26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35.],
       [36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45.],
       [46., 47., 48., 49., 50.]])